default: &default
  adapter: mysql2
  host: localhost
  port: 3306
  username: crmifc
  password: crmifc2016ru
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: crimeainfocom_development

test:
  <<: *default
  database: crimeainfocom_test

production:
  <<: *default
  database: crimeainfocom
